import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';

import '../core/config.dart';
import '../features/payment/screens/payment_waiting_screen.dart';
import 'campay_service.dart';

/// Result of a payment attempt.
class PaymentResult {
  const PaymentResult({
    required this.success,
    required this.status,
    this.txRef = '',
    this.transactionId = '',
  });

  /// Confirmed successful payment (status `successful`).
  final bool success;

  /// Final status: successful | failed | cancelled.
  final String status;

  /// External reference generated by the app.
  final String txRef;

  /// CamPay transaction reference (empty if not confirmed).
  final String transactionId;
}

/// Payment service — collects via the CamPay REST API (MTN MoMo /
/// Orange Money, Cameroon) then records the transaction in Firestore
/// (`transactions/{txRef}`), which feeds the "My Bill" history.
///
/// Flow: [charge] initiates collection on the client's phone
/// ([CampayService.initCollect]) then opens [PaymentWaitingScreen], which
/// polls CamPay until the client confirms (PIN).
class PaymentService {
  PaymentService({FirebaseFirestore? db, CampayService? campay})
      : _db = db ?? FirebaseFirestore.instance,
        _campay = campay ?? CampayService();

  final FirebaseFirestore _db;
  final CampayService _campay;

  /// True when the CamPay token has been configured.
  bool get isConfigured => _campay.isConfigured;

  /// Amount charged: in demo always 1 XAF (plan price is display-only).
  double demoChargeableAmount(double amount) =>
      AppConfig.isCampayDemo ? AppConfig.campayDemoMaxAmount : amount;

  /// Initiates a CamPay collection.
  ///
  /// - [phone]: client number in `+237...` format (normalized for
  ///   CamPay automatically).
  /// - [type]: `'subscription'` | `'pickup'` (transaction category).
  /// - [txRefPrefix]: external reference prefix (e.g. `WP`, `PICKUP`).
  ///
  /// Returns a [PaymentResult]; `success == true` only when CamPay
  /// confirms the payment (status SUCCESSFUL).
  ///
  /// Throws a [String] or [CampayException] if CamPay is not configured
  /// or if initiation fails.
  Future<PaymentResult> charge({
    required BuildContext context,
    required double amount,
    required String currency,
    String email = '',
    required String phone,
    String name = '',
    required String title,
    required String type,
    String description = '',
    String txRefPrefix = 'WP',
  }) async {
    if (!_campay.isConfigured) {
      throw 'CamPay is not configured. Build the app with '
          '--dart-define=CAMPAY_TOKEN=<your app token> '
          '(free demo token from demo.campay.net).';
    }
    if (amount <= 0) throw 'Invalid amount.';

    // CamPay sandbox: each transaction is capped at
    // [AppConfig.campayDemoMaxAmount] XAF (ER201 beyond that). In demo mode
    // we charge the cap instead of the real plan price — the full flow
    // (USSD → PIN → confirmation) remains testable end-to-end.
    // In production (`www.campay.net`) there is no cap: the real price goes through.
    final charged = demoChargeableAmount(amount);

    final txRef = CampayService.newExternalReference(txRefPrefix);
    final initiated = await _campay.initCollect(
      amount: charged,
      currency: currency,
      from: CampayService.normalizePhone(phone),
      description: description.isEmpty ? title : description,
      externalReference: txRef,
    );

    // Écran d'attente : le client confirme sur son téléphone (PIN USSD).
    if (!context.mounted) {
      return PaymentResult(success: false, status: 'cancelled', txRef: txRef);
    }
    final waiting = await Navigator.of(context).push<PaymentWaitingResult>(
      MaterialPageRoute(
        builder: (_) => PaymentWaitingScreen(
          service: _campay,
          reference: initiated.reference,
          amount: charged,
          currency: currency,
          ussdCode: initiated.ussdCode,
          operator: initiated.operator,
        ),
      ),
    );

    final status = waiting?.status ?? 'cancelled';
    final transaction = waiting?.transaction;
    final result = PaymentResult(
      success: status == 'successful',
      status: status,
      txRef: txRef,
      transactionId: transaction?.reference ?? '',
    );

    await recordTransaction(
      phone: phone,
      amount: charged,
      currency: currency,
      type: type,
      title: title,
      result: result,
    );
    return result;
  }

  /// Enregistre la transaction dans `transactions/{txRef}` (historique du
  /// client). Un échec d'écriture ne fait jamais échouer le flux de
  /// paiement (l'historique est best-effort).
  Future<void> recordTransaction({
    required String phone,
    required double amount,
    required String currency,
    required String type,
    required String title,
    required PaymentResult result,
  }) async {
    try {
      await _db.collection('transactions').doc(result.txRef).set({
        'txRef': result.txRef,
        'transactionId': result.transactionId,
        'phone': phone,
        'userId': phone,
        'amount': amount,
        'currency': currency,
        'type': type,
        'description': title,
        'status': result.status,
        'paymentMethod': 'campay',
        'createdAt': FieldValue.serverTimestamp(),
      });
    } catch (_) {
      // Silencieux : ne jamais bloquer l'utilisateur pour un historique.
    }
  }
}
