// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASh4XMhFvQ1h-ZG_gdE-nuuho_2h299os',
    appId: '1:107168223474:android:ff28accac53b102f74c06b',
    messagingSenderId: '107168223474',
    projectId: 'waste-pro-f67a5',
    storageBucket: 'waste-pro-f67a5.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVkLwEpFHhLQcrBECgHdrwhhIYRA7rDmg',
    appId: '1:107168223474:ios:1e776ec04f865cc874c06b',
    messagingSenderId: '107168223474',
    projectId: 'waste-pro-f67a5',
    storageBucket: 'waste-pro-f67a5.firebasestorage.app',
    iosBundleId: 'com.example.wastePro',
  );
  // Config web : réutilise l'app web-type déjà enregistrée dans le projet
  // (identifiants réels — l'ancien appId était un placeholder).
  // Recommandé en prod : `flutterfire configure` pour créer une app web
  // dédiée.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtZ2G7JI-XMHyWolGjLMtRMpbFBoq5Yhw',
    authDomain: 'waste-pro-f67a5.firebaseapp.com',
    projectId: 'waste-pro-f67a5',
    storageBucket: 'waste-pro-f67a5.firebasestorage.app',
    messagingSenderId: '107168223474',
    appId: '1:107168223474:web:f82fd3b32d6b5c1874c06b',
    measurementId: 'G-QWKH1V357T',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtZ2G7JI-XMHyWolGjLMtRMpbFBoq5Yhw',
    appId: '1:107168223474:web:f82fd3b32d6b5c1874c06b',
    messagingSenderId: '107168223474',
    projectId: 'waste-pro-f67a5',
    authDomain: 'waste-pro-f67a5.firebaseapp.com',
    storageBucket: 'waste-pro-f67a5.firebasestorage.app',
    measurementId: 'G-QWKH1V357T',
  );
}
